INFO:root:('Scoring started: ', time.struct_time(tm_year=2020, tm_mon=6, tm_mday=3, tm_hour=11, tm_min=52, tm_sec=35, tm_wday=2, tm_yday=155, tm_isdst=1))
INFO:root:Algorithm supervised: LogisticRegression_test_data_transformed_predict 
	accuracy:	0.8365458750963762
	 f1_macro:	0.8359109347525362
	recall_macro:	0.8361890745983673
	precision_macro:	0.841774430114439
INFO:root:                        precision    recall  f1-score   support

                Letter       0.85      0.81      0.83      2444
                  Form       0.80      0.79      0.79      2485
                 Email       0.95      0.92      0.94      2514
         Advertisement       0.74      0.70      0.72      2241
     Scientific report       0.82      0.76      0.79      2471
Scientific publication       0.90      0.87      0.89      2558
         Specification       0.94      0.90      0.92      2459
           File folder       0.55      0.89      0.68      1930
          News article       0.81      0.82      0.81      2447
                Budget       0.83      0.81      0.82      2457
               Invoice       0.88      0.86      0.87      2450
          Presentation       0.76      0.74      0.75      2471
         Questionnaire       0.90      0.87      0.88      2394
                Resume       0.99      0.96      0.98      2532
                  Memo       0.90      0.85      0.87      2463

              accuracy                           0.84     36316
             macro avg       0.84      0.84      0.84     36316
          weighted avg       0.85      0.84      0.84     36316

WARNING:root:('In load error open file: ', '/media/remote/tmandal/document-clustering-with-deep-neural-networks/python_objects/LogisticRegression_test_vector')
ERROR:root:[Errno 2] No such file or directory: '/media/remote/tmandal/document-clustering-with-deep-neural-networks/python_objects/LogisticRegression_test_vector.p'
ERROR:root:Found input variables with inconsistent numbers of samples: [36316, 0]
Traceback (most recent call last):
  File "scoring.py", line 62, in <module>
    main()
  File "scoring.py", line 55, in main
    run()
  File "scoring.py", line 30, in run
    accuracy = accuracy_score(y_true, predict)
  File "/media/remote/tmandal/document-clustering-with-deep-neural-networks/code/.venv/lib/python3.6/site-packages/sklearn/metrics/_classification.py", line 185, in accuracy_score
    y_type, y_true, y_pred = _check_targets(y_true, y_pred)
  File "/media/remote/tmandal/document-clustering-with-deep-neural-networks/code/.venv/lib/python3.6/site-packages/sklearn/metrics/_classification.py", line 80, in _check_targets
    check_consistent_length(y_true, y_pred)
  File "/media/remote/tmandal/document-clustering-with-deep-neural-networks/code/.venv/lib/python3.6/site-packages/sklearn/utils/validation.py", line 212, in check_consistent_length
    " samples: %r" % [int(l) for l in lengths])
ValueError: Found input variables with inconsistent numbers of samples: [36316, 0]
INFO:root:Scoring ended: time.struct_time(tm_year=2020, tm_mon=6, tm_mday=3, tm_hour=11, tm_min=52, tm_sec=35, tm_wday=2, tm_yday=155, tm_isdst=1)
INFO:root:('Scoring', ' executed for 00:00:00.45')
